jobs:
  main:
    requires: [~pr, ~commit, ~sd@1013523:main]
    image: node:8
    steps:
      - echo: echo hi
  other:
    requires: [~pr, ~commit, ~sd@1013523:promote]
    image: node:8
    steps:
      - echo: echo hi
  other2:
    requires: [~pr, ~commit, ~sd@1013523:test]
    image: node:8
    steps:
      - echo: echo hi
      
