jobs:
  main:
    requires: [~pr, ~commit, ~sd@3983:main]
    image: node:8
    steps:
      - echo: echo hi
  other:
    requires: [~pr, ~commit, ~sd@3983:promote]
    image: node:8
    steps:
      - echo: echo hi
  other2:
    requires: [~pr, ~commit, ~sd@3983:publish]
    image: node:8
    steps:
      - echo: echo hi
